config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'static_pages/about'

  get 'static_pages/faq'

  get 'static_pages/contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visit.rb
class Visit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @visits = Visit.all
  end

  def about
    @visits = Visit.all
  end


  def faq
    @visits = Visit.all
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "RoR Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.duckduckgo.com/">Duck Duck Go Search</a>
    and one and only <a href="http://www.KudosX.com/">KudosX</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "Contact", static_pages_contact_path %></li>
      <li><a href="http://www.KudosX.com">KudosX.com</a></li>
    </ul> </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", static_pages_about_path %></li>
        <li><%= link_to "FAQ", static_pages_faq_path %></li>
        <li><%= link_to "Contact", static_pages_contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name=“viewport” content=“width=device-width, initial-scale=1, maximum-scale=1”>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>and More Charts</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>


<div class="row">

  <!-- Pie Chart -->
  <div class="col-xs-9">
    <h3>Total Visits by Country</h3>
    <%= pie_chart @visits.group(:country).count %>
  </div>

</div>


<!-- area chart -->
<div class="row">
  <div class="col-xs-12">
    <h3>Total Load Time By Day</h3>
    <%= area_chart @visits.group_by_day(:visited_at).maximum(:load_time) %>
  </div>
</div>



<div class="row">
    <!-- Column Chart -->
    <div class="col-xs-6">
      <h3>Total Visits Per Country</h3>
      <%= column_chart @visits.group(:country).count %>
    </div>
    <!-- Bar Chart -->
    <div class="col-xs-6">
      <h3>Total Visits Per Country</h3>
      <%= bar_chart @visits.group(:country).count %>
    </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>
<h1>and The World</h1>

<div class="row">

  <!-- Geo Chart -->
  <div class="col-xs-12">
    <h3>Visits By Day</h3>
    <%= geo_chart @visits.group(:country).count %>
  </div>

</div>

app/views/static_pages/index.html.erb
<% provide(:title, 'Home') %>
<h1>Admin Page</h1>
<p>TimeLine using google charts and chartkick</p>

<%= timeline [
                 ["Washington", "1789-04-29", "1797-03-03"],
                 ["Adams", "1797-03-03", "1801-03-03"],
                 ["Jefferson", "1801-03-03", "1809-03-03"]
             ] %>

<h2> Line Charts</h2>
<div class="row">

  <!-- Line Chart - Single Series -->
  <div class="col-xs-12">
    <h3>Visits By Day</h3>
    <%= line_chart @visits.group_by_day(:visited_at, format: "%B %d, %Y").count, discrete: true %>
  </div>

  <!-- Line Chart - Multiple Series -->
  <div class="col-xs-12">
    <h3>Visits By Country Per Day</h3>
    <%= line_chart   Visit.pluck("country").uniq.map { |c| { name: c, data: @visits.where(country: c).group_by_day(:visited_at, format: "%B %d, %Y").count }  }, discrete: true %>
  </div>

</div>


<h2>Pie this</h2>
<%= pie_chart({"Football" => 10, "Basketball" => 5}) %>